wireviz/WireViz

src/wireviz.py
One possible solution for custom pin numbering, e.g. fits needs in #4 
- Pincount is detected automatically if not given.
- If both, pinout and pinnumbers, are given, their count must match.
- Freedom to give pin numbers in any order, in alphabetical and mixed notation.
Sample
```
connectors:
X1:
type: D-Sub
subtype: male
pincount: 25
pinnumbers: [1,14,3,16,5,18,7,20,9,22,11,24,13]
pinout: [ SENSE_P_1, SENSE_N_1, SENSE_P_2, SENSE_N_2, SENSE_P_3, SENSE_N_3, SENSE_P_4,SENSE_N_4, SENSE_P_5, SENSE_N_5, SENSE_P_6, SENSE_N_6, GND ]
X2:
type: F48
subtype: female
pincount: 48
pinnumbers: [ z2,b2,d2,z4,b4,d4,z6,b6,d6,z8,b8,d8,z10,b10,d10,z12,b12,d12,z14,b14,d14,z16,b16,d16,z18,b18,d18,z20,b20,d20,z22,b22,d22,z24,b24,d24,z26,b26,d26,z28,b28,d28,z30,b30,d30,z32,b32,d32 ]
cables:
W1:
gauge: 0.25 mm2 …
```
=> Add optional custom pinnumbers to connector

.github/workflows/main.yml
This add a Github Actions workflow which 
- sets up an Ubuntu image with graphviz & Python 3.7 + 3.8
- runs `build_examples.py` as an integration test
- is executed on each pull/pull request
The workflow can be extended to run some helpful analysis tools, e.g. `pylint` (Python linter), `mypy` (Pyhton type checking), `black` (format checker).
=> [ci] Add Github Actions

src/wireviz/wireviz.py
This fixes #33 where designators appear across all wires of a guage rather than just the ones that use that colour.
The result of the testcase in that issue can be seen below.
=> Fix for Designators apearing across all colours of wires of a guage.

src/wireviz/Harness.py, src/wireviz/wv_helper.py
Three suggested independent commits that affect generation of BOM:
1. Correct a wrong TODO statement.
2. Remove bundle grouping as it is not needed for the wire grouping. 
As long as the wires can be grouped across bundles, 
grouping the bundles has no purpose, as the same
wires can be collected by just looping all bundles. 
3. Allow one common value or list of values for each wire. 
Allow one common value when they are equal for all wires, 
e.g. the manufacturer is often equal for all wires, 
or a list of values to allow each wire a different value.
=> BOM simplifications

examples/demo02.yml, src/wireviz/Harness.py, tutorial/tutorial06.yml
This paves the way to make wire splicing (#26) look better, and shows an elegant solution to how color marks for connectors or individual connector pins (#53) might be implemented.
=> Refactor ferrule output code generation, make more flexible

src/wireviz/Harness.py, src/wireviz/wireviz.py
This implements #51. An example of an additional bom line is shown below. 
```
additional_bom_items:
-
description: Label, pinout information
qty: 2
unit: ea
designators:
- X2
- X3
manufacturer: generic company
manufacturer_part_number: Label1
internal_part_number: Label-ID-1
```
=> Add ability to include aditional bom lines.

src/wireviz/Harness.py
Address issue #82 
As directed by author, `filename` is a complete path.
=> Make file output more consistently behaved.

src/wireviz/Harness.py, src/wireviz/wireviz.py
In creating the GUI, I am attempting to pull information from the `Harness` class.  The `parse` function throws away the `Harness` instance and I am trying to get access to that information.
=> Add ability for `parse` to return the `Harness` instance

src/wireviz/build_examples.py
build_examples supports cleaning examples and intelligently will detect new examples.
SUGGESTION: When merging into dev, require
```
build_examples.py clean
```
and then only build when merging into master branch
This should allow easier merges, especially from windows, and I am using it as part of a resolution to one of the requests in #17
=> Allow cleaning of examples

src/wireviz/Harness.py
Fix issue #97 
- Remove XML and DOCTYPE declarations from embedded SVG
- Add DOCTYPE declaration in HTML output
=> Avoid Improper XML and DOCTYPE Declarations

src/wireviz/wv_colors.py
This might be useful for some more exotic [ferrule colors](https://de.wikipedia.org/wiki/Aderendh%C3%BClse#Farbliche_Markierung)
=> Add new colors (olive green, light blue, beige, ivory)

src/wireviz/Harness.py
Closes #69.
Probably just an interim solution until work on #66 continues, and a more elegant fix arises.
=> Fix node rendering for cables with hidden name and/or no visible attributes

src/wireviz/wv_colors.py
...when no color is specified.
Fixes the bug seen in the [previous PR](https://github.com/formatc1702/WireViz/pull/104#pullrequestreview-451542527) of `#ffffff` appearing inside the node when wire colors are not specified.
=> Fix HTML color code appearing in wire node

src/wireviz/Harness.py
As the spline shield wires are rendered as thin tinned wires with black borders, and the shield wires in cable nodes were rendered as a single (bottom) border, they didn't fit well together, e.g. in [tutorial03.png](https://github.com/formatc1702/WireViz/blob/dev/tutorial/tutorial03.png):
The shield wires in cable nodes are now rendered equally as the spline shield wires. The default behavior is now kept as before multi-colors were introduced. This is tutorial03.png produced after the fix:
The new feature is that `cable.shield` is allowed to contain a two-letter color code to specify a colored shield wire with black borders. This is tutorial03.png produced from a modified YAML file:
```diff
--------------------------- tutorial/tutorial03.yml ---------------------------
index …
```
=> Make each shield wire uniform and allow cable.shield color

src/wireviz/build_examples.py, src/wireviz/wv_helper.py
This PR ~~builds on top of #110 and~~ add some new features:
- Add `compare` action to compare generated files (except those generated by Graphviz unless using `-c`) against git repository.
- Add `restore` action to restore generated files from git repository.
- Make all actions honor the optional argument `-g`. This make it possible to select the group of files to use for any action by following the action argument with `-g` and then the space separated group names.
Edit: It should not break the existing `build` and `clean` actions, but their algorithms to collect files are slightly adjusted so they can use a common function to reduce code duplication.
These new features are useful for #63, but does not close it (collecting corner cases are also needed).
Edit 2: A few extra changes seen …
=> Extended build examples

src/wireviz/Harness.py
Addresses #131.
Previously, padding of single-color wires to match thickness of multicolor ones was decided on a per-cable basis.
This PR changes the behavior to a global, per-harness basis; i.e. if any wire in the entire harness is multicolored, and thus will be rendered thicker, all other wires are padded to match.
=> Change wire padding behavior

src/wireviz/wv_colors.py
print out the color string that cannot be found so the user has it easier to fix typos.
=> extend unknown color error message

setup.py, src/wireviz/__init__.py, src/wireviz/build_examples.py, src/wireviz/wireviz.py
=> Change command line options

src/wireviz/Harness.py, src/wireviz/wv_helper.py
This simplification of the colorbar was originally committed in #153 to demonstrate the power of a new internal feature developed for images, and now pushed as a separate PR as requested by @formatc1702 in this comment:
I am not against this change, but it probably should be a separate PR since it is unrelated to the image issue
_Originally posted by @formatc1702 in https://github.com/formatc1702/WireViz/pull/153#discussion_r470473124_
=> [internal] Html colorbar

examples/ex05.yml, src/wireviz/Harness.py, src/wireviz/wv_helper.py, tutorial/tutorial08.yml
This change will remove HTML links from the input attributes when generating graphs with GraphViz (because it does not support this HTML tag).
This way these links could be used generated the HTML BoM table (basically without changing the input) where they could be useful.
```
connectors:
X1:
type: '<a href="https://www.digikey.com/product-detail/en/stewart-connector/SS-37000-002/380-1098-ND/1033365">Stewart Connector SS-37000-002</a>'
subtype: male
pinlabels: [DA+,DA-,DB+,DC+,DC-,DB-,DD+,DD-] # pincount is implicit in pinout
X2:
type: '<a href="https://www.digikey.com/product-detail/en/stewart-connector/SS-37000-002/380-1098-ND/1033365">Stewart Connector SS-37000-002</a>'
subtype: male
pinlabels: [DB+,DB-,DA+,DD+,DD-,DA-,DC+,DC-]
```
Results:
BTW.  it might be useful to add some links to …
=> Remove HTML links from the input attributes 

src/wireviz/DataClasses.py
=> Update the types of dataclass attributes according to usage

src/wireviz/DataClasses.py, src/wireviz/Harness.py
Closes #53.
Based on `feature/gv-html-refactor` branch.
- Adds new `pincolors` list attribute to connectors.
- If `pincolors` is used, needs to be the same length as `pins`, `pinlabels`
- If used, displays a small color mark and label next to each pin
- Color mark is smaller than the `connector.color` mark on purpose
- Implements `__` as placeholder for pins with no color
- Better suggestions welcome
- Edit 2020-10-21: Any unknown color code is treated as "no color", so `__`, `--`, `XX` and anything else may be used.
- Makes sure white color marks look decent on white background
- TODO in the future: detect what background color is used, and react accordingly
Example:
```yaml
connectors:
X1:
type: D-Sub
subtype: female
color: GY
pins:      [5,   2,  3,  99,  98,  97,  96,  95,  94] …
```
=> Add option to add colors to connector pins

examples/ex08.yml, src/wireviz/DataClasses.py, src/wireviz/Harness.py
Closes #70.
Closes #169.
Closes #193.
=> Reference wires by color or label

src/wireviz/DataClasses.py, src/wireviz/Harness.py, src/wireviz/wv_bom.py, src/wireviz/wv_gv_html.py, src/wireviz/wv_helper.py, src/wireviz/wv_html.py
=> Move BOM management and HTML functions to separate modules

src/wireviz/DataClasses.py, src/wireviz/Harness.py, src/wireviz/wv_bom.py
- This solves the basic part of #7
- It is based on #161, #162, and #171 and solves the known bugs commented in their reviews
- The commits are rebased on top of the current `dev`
- The bug about adding quantities of different units was fixed as part of the conflict resolution during rebasing
- The two commits by @zombielinux from #161 and #162 are squashed into one with authorship unchanged
- The merge commit by @stevegt disappeared during rebasing, but his real change commit is present with authorship unchanged
=> Length unit

src/wireviz/DataClasses.py
Built on new `length_unit` attribute from #196.
=> Detect and assign unit within cable length attribute

src/wireviz/DataClasses.py
Bug: Failing to assign the default cable length unit when not present.
It was introduced in #198.
Fix: Test the correct cable attribute. This fix solves issue #205.
=> Assign the default cable length unit when not present

src/wireviz/DataClasses.py
If `show_wirenumbers` is omitted from a cable section, its value will be `None`. In that case, we want to choose a default based on whether this is a bundle or not.
If the user did specify `show_wirenumbers`, then its value will be `True` or `False`, and we want to respect that whether it's a bundle or not.
=> Correctly check for show_wirenumbers default of None

src/wireviz/Harness.py
**Bug**: Hiding connector pins when none are connected is not reasonable. When combined with loops or neither pinlabels nor pincolors, then exceptions are raised as well.
**Fix**: Forcing pins at the left side in such cases solves #217.
=> Show connector pins even when all are unconnected

docs/CHANGELOG.md, docs/syntax.md
The aim of this branch is to advance in parallel to the `dev` branch as PRs are merged and features added.
This can include expanding the syntax description (`syntax.md`), the changelog (`CHANGELOG.md`), the general readme (`README.md`) or others.
Before a release, this branch can be then squashed and rebased onto `dev` to reflect all the updates included in that release.
The idea is to prevent cluttering the commit history with individual commits from each PR documenting itself (`Add #xxx to changelog`, `Expand syntax description to reflect new feature from #yyy`). It remains to be seen whether this is a good idea, and I am open to feedback on this topic.
=> Continuous documentation

docs/CHANGELOG.md, src/wireviz/DataClasses.py, src/wireviz/Harness.py
Closes #160.
Use unique numerical index instead of string (which might cause issues when using pin names that are not unique when ignoring upper/lower case).
This does not address the issue of having special HTML characters as part of pin names, labels, etc. [as mentioned in #160](https://github.com/formatc1702/WireViz/issues/160#issuecomment-725544366) and now listed as #230; there should be a separate PR dealing with escaping these entities in the GraphViz HTML (e.g. `>` to `&gt;`).
=> Use unique index for connector pin ports

docs/syntax.md, src/wireviz/DataClasses.py, src/wireviz/Harness.py, src/wireviz/wireviz.py
- Solves #174 intermediately by allowing low level .gv tweaking.
- See https://github.com/formatc1702/WireViz/issues/174#issuecomment-707372543 and [HDMI_Sideband_Tap_tweaked.txt](https://github.com/formatc1702/WireViz/files/7130401/HDMI_Sideband_Tap_tweaked.txt) for an example usage and suggested changes of `syntax.md` for accepted input value types.
- This tweak feature is not limited to what I suggest in that example usage. It enables overriding any main attribute of any entry in the generated `.gv` file, and appending any number of custom entries, e.g. nodes, edges, and subgraphs. Overriding entries with attributes containing HTML is not tested, and will probably need more advanced functionality, but no such plans without any requests.
- Please check that attributes and custom entries …
=> Add optional tweaking of the .gv output

docs/syntax.md, src/wireviz/DataClasses.py, src/wireviz/Harness.py, src/wireviz/wv_bom.py, src/wireviz/wv_colors.py, src/wireviz/wv_gv_html.py
- This solves #210 completely by supporting bgcolor of both the node title
and the whole node independently using separate attributes (`bgcolor_title` and `bgcolor`).
- Supporting `bgcolor` of an image to enable adapting the table cell background to the image background.
- ~~To make it easier choosing background colors, I suggest adding more light colors into `_color_hex`.~~ (hex input is now possible)
- ~~I suggest merging both #197 and #214 before rebasing this PR on top, and then possibly add an extra commit here before it might be ready.~~ (done)
Example usage together with other color attributes:
<details>
<summary>Click to expand YAML input</summary>
```yaml
connectors:
X1: &conn
pinlabels: [+5V, GND]
bgcolor: IV  # Node background color
X2:
<<: *conn
bgcolor_title: YE  # Title row …
```
=> Add bgcolor attribute to connectors and cables

setup.py, src/wireviz/build_examples.py, src/wireviz/wireviz.py
=> Replace `os.path` with `pathlib.Path`

src/wireviz/Harness.py, src/wireviz/svgembed.py, src/wireviz/wv_html.py
[Update 2020-11-16]
This PR has evolved from simply fixing how relative image paths are resolved, to embedding any images in the SVG file by default, eliminating the original issue.
---
Previously, paths to images were resolved relatively to the specified _output_ file instead of the _input_ file.
This produces errors when calling WireViz with the `-o` flag, creating output files in a different location from the input.
This PR [partially, see comment below] fixes the problem.
Additionally, it eliminates the need for passing a `gv_dir` variable to the `Image` class, resolving paths beforehand and passing the absolute path to the `Image` class.
=> Embed images in SVG output

src/wireviz/wireviz.py
I think OSError had an update at some point, and the error code the program looks for changed. Anyhow this change fixes the titleblock-added version of the program.
=> Use portable OS error codes so program doesn't crash

docs/syntax.md, src/wireviz/DataClasses.py, src/wireviz/wv_bom.py
qty_multiplier can be set to `unpopulated` when defining additional connector components. This will calculate the number of empty pin spaces in the connector.
I use this for waterproof connectors which require sealing plugs to be installed in unoccupied sockets.
=> Add unpopulated option to additional components qty multiplier

src/wireviz/wireviz.py
Suggested fix posted in
https://github.com/wireviz/WireViz/issues/344#issuecomment-2113476151
Please verify that this fixes #344 and report back.
~~The base branch of this PR is `master` for the time beeing, but it should be changed to a new release/v0.4.1-rc before any merge-in. #345 should also be fixed and updating the changelog before releasing the hotfix.~~
=> Handle OSError [errno.EINVAL] that might be raised in Windows

src/wireviz/wireviz.py
The CLI handling code was redesigned for v0.4 and it seems the code to assign a default title from v0.3.1 has been messed up. This bug has not been triggered by `build_examples.py` due to it seems to call the `parse()` function differently.
The `output_name` should be used as default title when present.
This will fix the #360 bug report.
=> Use output_name as default title

setup.py
Specify all HTML files under templates folder to be included as package data files.
Is this sufficient to fix #345? Some sources claim that `include_package_data=True` also is needed, but preliminary testing at my Windows setup seems to prove otherwise. I would prefer that some others could confirm at different platforms and versions.
Please, anyone, test this branch at the platform(s) you have access to, and report back here the output from all commands. See the simple installation command in https://github.com/wireviz/WireViz/pull/347#issuecomment-2152259121 below.
Alternatively, a longer and more complicated test procedure is suggested a bit earlier below, and if you don't have `git` installed, you can replace the `git clone` command with unpacking all files from [this …
=> Add template files to package

src/wireviz/Harness.py
Harness.py uses embed_svg_images without importing it first.
Edit:
wireviz 0.4
python 3.11.9
dot - graphviz version 11.0.0 (20240428.1522)
It occurs as issue if you embed wireviz in a python script
e.g.:
```python
from wireviz.wireviz import parse
y = """---
connectors:
X1:
type: D-Sub
subtype: female
pinlabels: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
X2:
type: Molex KK 254
subtype: female
pinlabels: [GND, RX, TX]
cables:
W1:
gauge: 0.25 mm2
length: 0.2
color_code: DIN
wirecount: 3
shield: true
connections:
-
- X1: [5,2,3]
- W1: [1,2,3]
- X2: [1,3,2]
-
- X1: 5
- W1: s
"""
```
```python
parse(y, return_types="svg", output_name="test.svg")
Traceback (most recent call last):
File "C:\Users\adaemmer\git\test\wireviz_demo.py", line 32, in <module>
parse(y, return_types="svg", …
```
=> [Bug] add missing import of embed_svg_images

src/wireviz/wv_bom.py
Sometimes the total length of certain items in the BOM will be shown with a decimal point and a trailing zero even if all values are input as integers. One source of this is https://github.com/wireviz/WireViz/blob/v0.4/src/wireviz/DataClasses.py#L310 where an integer value will be converted to a float value, but there might be other places in the code that could cause the same issue.
This change will resolve the issue at the other end (while processing the BOM) - independently of what might be the source of the issue. This should fix #340.
=> Avoid decimal point and trailing zero for integer BOM quantities

docs/syntax.md, src/wireviz/svgembed.py, src/wireviz/templates/README.md, src/wireviz/wv_html.py
This will e.g. enable users to replace SVG diagram with PNG, that is needed as a work-around when the SVG output from Graphviz is not looking good. Suggested as work-around for Graphviz bug in https://github.com/wireviz/WireViz/issues/175#issuecomment-2132206026
=> Add HTML template placeholders for filename

src/wireviz/Harness.py
This bug was reported in #257 more than 2.5 years ago, but is still present in v0.4, and can be triggered by e.g. this YAML input:
```yaml
connectors:
X1:
pincount: 2
hide_disconnected_pins: true
connections:
- - X1
```
Graphviz reports an error when the HTML table of pins is empty.
This minor change should fix #257
=> Avoid Graphviz error when hiding all pins

src/wireviz/Harness.py
Work-around to improve the #286 use case.
=> Add non-empty label to avoid over-sized loops

src/wireviz/Harness.py
The code processing mates used a mix of repeated connector look-ups and local connector variables, and one variable was used before it was assigned the correct value.
This error was detected when investigating the #355 bug report.
that caused some generated dot output to be unavailable for tweaking. A fix for that is now pushed as a separate commit into this PR.
=> Fix bugs in mate processing

src/wireviz/templates/README.md, src/wireviz/templates/din-6771.html, src/wireviz/wv_html.py
@formatc1702 must must check if this suggested change (placeholder name consistency) is OK, or if it might have some bad side-effects. If there is a good reason to keep this one placeholder very different from the others, then that reason should be explained in a code comment.
A bonus advantage by using the name ``, is that it will be easy to later generalize by letting any string or numeric `metadata.{item}.{key}` entry replace the corresponding `` placeholder.
~TODO: If both PR #371 and this PR is accepted, then the `templates/README.md` file must be updated.~ (it is now updated)
Fixes #377
=> Rename placehoder "sheetsize_default" to <!-- %template_sheetsize% -->

src/wireviz/wireviz.py
Add ValueError and OSError where `e.errno` is `None` to Exception Handling of `_get_yaml_data_and_path()`
**This PR is amending fixes for the following issues based on #250 and #318.**
- https://github.com/wireviz/WireViz/pull/318#pullrequestreview-1457016602
describing 80000 character YAML input raising `ValueError`
- https://github.com/wireviz/WireViz/issues/391#issuecomment-2180419249 
describing `OSError: _getfinalpathname: path too long for Windows` 
```
```
`master` contains #250 from d7d7854bce39881a970b54e3522d9293441c5ce1: Consolidate wireviz.parse() to handle Path, str and Dict as input
https://github.com/wireviz/WireViz/blob/954c4f5f92b1d0531f6af0c318c60786b7906d42/src/wireviz/wireviz.py#L415
`release/v0.4.1-rc` contains #318 at 6f9007f45d48cc65f3469b362976bb53ac1cd7e0: Use …
=> Fix Exception Handling in _get_yaml_data_and_path(...)

src/wireviz/Harness.py, src/wireviz/svgembed.py, src/wireviz/wireviz.py, src/wireviz/wv_cli.py, src/wireviz/wv_helper.py, src/wireviz/wv_html.py
A number of such warnings showed up when running (with wireviz v0.4) e.g.
```sh
PYTHONWARNINGS=always python build_examples.py
PYTHONWARNINGS=always wireviz ../../examples/demo0?.yml
```
See https://github.com/wireviz/WireViz/pull/309#issuecomment-2170988381
Fix: All `open()` calls should be in a "`with open() as x`" statement to ensure closing the file when exiting the block in any way. Otherwise, use the new `file_read_text()` or `file_write_text()` thin wrapper functions to read or write the whole utf-8 text file and closing it.
=> Avoid ResourceWarning: unclosed file

.github/workflows/main.yml
**Running 6 different Python versions (3.7 to 3.12) in parallel now.** 
NOTE: This is in conflict with #309, but can be resolved easily.
GitHub Actions require an update:
- actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. 
- Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. 
- Updating this comes with a breaking change in upload-artifact@v4:
**_Uploading to the same named Artifact multiple times._**
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
**The artifact .zip files therefore have the python version added to their …
=> Update deprecated GitHub Actions and add Python versions
